config/routes.rb
Rails.application.routes.draw do
  resources :baanshares,shallow: true do
    member do
      post :pay_all
      post :pay
    end
    resources :wongshares do
      member do
        post :bit
        post :pay
      end
    end
  end
  get 'baanshares/:id', to: 'baanshares#show'
  post '/:id/delete', to: 'baanshares#delete'
  post 'baanshares/new', to: 'baanshares#new'
  get 'summary/', to: "summary#index"
  get 'wongshare/new', to: 'wongshares#new'
  post '/wongshare/new/', to: 'wongshares#new'
  patch 'wongshares/:id/edit', to: 'wongshares#edit'
  devise_for :accounts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "main#index"
  # get '/accounts/sign_in', to: 'sessions#new'
  # post '/accounts/sign_in', to: 'sessions#create'
end

app/controllers/baanshares_controller.rb
class BaansharesController < ApplicationController
    def index
        puts 'eeeeeeeeeeee'
        puts params
        puts 'eeeeeeeeeeee'
        @baansToday = Baan.getAllBaanToday(params[:id])
        @baansOtherDay = Baan.getAllBaanOtherday(params[:id])
    end

    def show
        @baanId = params[:id]
        baan = Baan.find_by_id(@baanId)
        @wongs = baan.getAllWong
    end
    def new 
        @baan = Baan.new
        if params[:baan]
            if @baan.update(params.required(:baan).permit(:name, :tel,:account_id))
                
              @baan.save!
      
              flash[:success] = "สร้างบ้าน #{@baan.name} สำเร็จ !!!"
              redirect_to baanshare_path(@baan.id)
              puts 'nnnnnnnnnnnnnnnnnnnn'
            end
          end
    end
    def delete
        @baanId = params[:id]
        baan = Baan.find_by_id(@baanId)        
        params[:w_ids] ||= []
        baan.delete(params[:w_ids]) if params[:w_ids].length > 0
        @wongs = baan.getAllWong
        redirect_to baanshare_path(params[:id])
    end

    def pay(*args)
        if params[:b_id].present?
            wong = Wong.find_by_id(params[:w_id])
            if wong.play_cycle == nil
                wong.play_cycle = wong.getCurrentCycle
            end
            if wong.paid == 0 #ถ้ายังไม่เคยจ่าย
                payUpdated = wong.interest
                if wong.fee_type === "จ่ายงวดแรก"
                    payUpdated += wong.fee
                end
            else
                payUpdated = wong.paid + wong.interest
                if wong.fee_type === "จ่ายงวดรับเงิน" && wong.play_cycle == wong.getCurrentCycle
                    payUpdated += wong.fee
                end
            end
            if wong.update(paid: payUpdated,status: true)
                flash[:success] = "ส่งยอดวง#{wong.name} เรียบร้อย!!"
                wong.save!
            else
                notice[:error] = "เกิดข้อผิดพลาด กรุณาลองอีกครั้ง"
            end
            redirect_to baanshare_path(params[:b_id])
        else
            args[0].each do |id|
                wong = Wong.find_by_id(id)
                if wong.paid == 0
                    payUpdated = wong.interest + wong.fee
                else
                    payUpdated = wong.paid + wong.interest
                end
                if wong.update(paid: payUpdated,status: true)
                    flash[:success] = "ส่งยอดวง#{wong.name} เรียบร้อย!!"
                    wong.save!
                else
                    notice[:error] = "เกิดข้อผิดพลาด กรุณาลองอีกครั้ง"
                end
            end
            redirect_to baanshare_path(params[:id])
        end
    end

    def pay_all
        baan = Baan.find_by_id(params[:id])
        wongs = baan.getAllWong
        puts 'pppppppppppppppppp'
        puts baan.getAllWongIds(wongs)
        puts 'pppppppppppppppppp'
        pay(baan.getAllWongIds(wongs))
    end
end

app/views/baanshares/_table.html.erb
<%# Data Table %>
<div class="border-b shadow-md border-gray-400 h-full">
    <%= form_with url:"/#{baanId}/delete" do |f|%>
        <table class="table-fixed border-collapse text-sm">
            <thead class="border-b-2 border-gray-300 shadow-md text-lg">
                <tr class="border-b text-gray-700 dark:text-gray-50">
                    <th><%= check_box_tag "w_ids[]", '', class: ''%></th>
                    <th class="w-2/12">ชื่อวง</th>
                    <th class="w-2/12 hidden md:table-cell">ประเภท</th>
                    <th class="w-2/12 ">ยอดส่ง</th>
                    <th class="w-3/12 hidden md:table-cell md:w-72">เงินต้น</th>
                    <th class="w-2/12">งวดต่อไป</th>
                    <th class="w-3/12">จัดการ</th>
                </tr>
            </thead>
            <tbody class="text-center text-gray-700 dark:text-gray-50 border-none">
                    <% @wongs.each do |w,index|%>
                        <tr class="">
                            <td><%= check_box_tag "w_ids[]", w.id, class: 'checkbox'%></td>
                            <td class=" break-all hover:text-blue-500 
                            cursor-pointer">
                                <a data-method="get" href= <%= wongshare_path(w.id,:baanId =>@baanId) %> 
                                class="md:py-4 block">
                                    <%= w.name %>
                                </a>
                            </td>
                            <td class="hidden md:table-cell md:py-4 break-all"><%= w.wong_type%></td>
                            <td class="md:py-4"><%= w.interest%></td>
                            <td class="hidden md:table-cell md:py-4"><%= w.deposite%></td>
                            <td class="md:py-4"><%= w.nextCycle().strftime('%d/%m')%><span class="inline md:hidden"><%= w.nextCycle().strftime('/%y')%></span><span class="hidden md:inline"><%= w.nextCycle().strftime('/%Y')%></span></td>
                            <td class="md:py-4 flex flex-col md:flex-row p-1 items-center justify-center">
                                <div>  
                                    <% if w.isActionDay() && w.status == false%>
                                        <%= button_to "ส่ง", pay_baanshare_path(w_id: w.id), method: :post , remote: true,
                                        class: "min-w-max flex-none 
                                            md:mr-2 mb-1 md:mb-0 
                                            transition-all duration-200 
                                            border border-green-500 rounded-sm
                                            mx-1 px-4 cursor-pointer 
                                            text-md text-gray-100 
                                            bg-green-500
                                            hover:text-white hover:bg-green-600 hover:border-green-600
                                            shadow-md"
                                        %>
                                    <%else%>
                                        <%= button_to "ส่ง", pay_baanshare_path(w_id: w.id), method: :post , remote: true,
                                        class: "pointer-events-none min-w-max flex-none 
                                            md:mr-2 mb-1 md:mb-0 
                                            transition-all duration-200 
                                            border border-gray-300 rounded-sm
                                            mx-1 px-4 cursor-pointer 
                                            text-md text-gray-100 
                                            bg-gray-300
                                            dark:bg-gray-800
                                            shadow-md"
                                        %>
                                    <%end%>
                                </div>
                                <%= form_with model: w, url: bit_wongshare_path(id: w.id,baanId: @baanId), method: :post, class: " flex flex-row justify-center" do |form|%>
                                    <%if w.bit == 0 && w.isActionDay() && w.getCurrentCycle != 0 && ! (w.wong_type === 'ขั้นบันได') && ! (w.wong_type === 'ดอกตาม')%>
                                            <%= form.text_field :bit, placeholder: "ราคาบิท", class: "w-full mx-3 my-1 md:my-0 md:mx-0 px-1 
                                            transition-all duration-200 
                                            text-xs text-center 
                                            border rounded-sm outline-none
                                            dark:bg-gray-800" %>
                                            <%= form.submit "บิท", class: "hidden md:block min-w-max 
                                            transition-all duration-200 
                                            border border-green-500 rounded-sm
                                            mx-1 px-4 cursor-pointer 
                                            text-md text-gray-100 
                                            bg-green-500
                                            hover:text-white hover:bg-green-600 hover:border-green-600
                                            shadow-md" %>
                                    <%else%>
                                            <%= form.text_field :bit, placeholder: "ราคาบิท", class: "pointer-events-none opacity-90 w-full mx-3 my-1 md:my-0 md:mx-0 px-1 
                                            transition-all duration-200 
                                            text-xs text-center 
                                            border rounded-sm outline-none
                                            dark:bg-gray-800" %>
                                            <%= form.submit "บิท", class: "pointer-events-none opacity-90 hidden md:block min-w-max 
                                            transition-all duration-200 
                                            border border-gray-300 rounded-sm
                                            mx-1 px-4 cursor-pointer 
                                            text-md text-gray-100 
                                            bg-gray-300
                                            dark:bg-gray-800
                                            hover:text-white hover:bg-green-600 hover:border-green-600
                                            shadow-md" %>
                                    <%end%>
                                <%end%>
                            </td>
                        </tr>
                    <%end%>
            </tbody>
        </table>
        <%if @wongs == nil%>
            <div class="flex justify-center w-full py-20">
                <span>ไม่มีข้อมูล</span>
            </div>
        <%else%>
            <div class="flex justify-end w-full pr-1">
                <%= f.submit 'ลบ',data: { confirm: "ยืนยันการลบวง?"}, remote: true, 
                class:'flex justify-end p-2 transition-all duration-200 
                    border-none
                    mx-1 px-8 cursor-pointer 
                    text-sm text-gray-900 underline
                    bg-gray-50
                    dark:bg-gray-800'%>
            </div>
        <%end%>
    <%end%>
</div>

app/views/baanshares/delete.js.erb
container = document.querySelector('.contain');
container.innerHTML = ("<%= j (render partial: 'table', locals:{wongs: @wongs, baanId: @baanId}) %>")

app/views/baanshares/index.html.erb
<div class="flex flex-col w-full my-5">
    <h1>บ้านแชร์วันนี้</h1>
    <%= render partial: '/shared/card', locals: {baans: @baansToday}%>
    <h1>บ้านแชร์วันอื่น ๆ</h1>
    <%= render partial: '/shared/card', locals: {baans: @baansOtherDay}%>
</div>

app/views/baanshares/new.html.erb
<div class="flex flex-col w-full my-5">
    <div class="flex flex-row justify-between md:justify-center">
        <h1 class="text-center text-2xl">สร้างบ้านใหม่</h1>
        <%=link_to 'ยกเลิก', :back, class: '
            md:absolute md:right-5
            min-w-max 
            transition-all duration-200 
            border rounded-sm border-8 border-green-500 
            px-8 mx-1 
            cursor-pointer
            bg-white
            text-md text-gray-900
            shadow-md'%>
    </div>
    <%= form_for @baan, url: new_baanshare_path(), local: true, class: "h-full" do |f| %>
            <%= f.hidden_field :account_id, value: current_account.id%>
            <div class="w-full my-5 text-gray-900 dark:text-white ">
                <div class="flex flex-col w-full">
                    <div class="flex flex-col mb-5">
                        <%= f.label 'ชื่อบ้าน:', class: 'font-bold text-lg'%>
                        <%= f.text_field :name, required: true, placeholder: "กรอกชื่อวง", class: 'border-b-2 focus:border-green-500 text-center outline-none bg-white dark:bg-gray-700 dark:text-gray-100 py' %>
                    </div>
                    <div class="flex flex-col mb-5">
                        <%= f.label 'เบอร์มือถือ:', class: 'font-bold text-lg'%>
                        <%= f.text_field :tel, placeholder: "กรอกเบอร์มือถือ", class: 'border-b-2 focus:border-green-500 text-center outline-none bg-white dark:bg-gray-700 dark:text-gray-100 py' %>
                    </div>
                </div>
                <%= f.submit 'สร้างบ้าน', class: 'min-w-max 
                    transition-all duration-200 
                    border rounded-sm border-8 border-green-500 
                    px-4 py-3
                    cursor-pointer
                    bg-green-500
                    text-lg text-gray-100
                    hover:text-white hover:bg-green-600
                    shadow-md'
                %>
            </div>
        <%end%>
    </div>

app/views/baanshares/show.html.erb
<div class="flex flex-col w-full">
    <%# Action bar %>
    <div class="flex justify-end my-3 ">
        <%= button_to 'ส่งทั้งหมด', pay_all_baanshare_path(wongs: @wongs), method: :post , remote: true,
        class: "min-w-max 
        transition-all duration-200 
        border rounded-sm border-8 border-green-500 
        px-4 mx-1 
        cursor-pointer
        bg-green-500
        text-md text-gray-100
        hover:text-white hover:bg-green-600
        shadow-md"
        %>
        <%= link_to "สร้างวง", wongshare_new_path(baanId: @baanId), :class => "min-w-max 
        transition-all duration-200 
        border rounded-sm border-8 border-blue-500 
        px-4 mx-1
        cursor-pointer
        bg-blue-500 
        hover:text-white hover:bg-blue-600
        text-md text-gray-100
        shadow-md"%>
    </div>
    <div class='contain'>
        <%=render partial: 'table', locals:{wongs:@wongs, baanId:@baanId}, class:'partial'%>
    </div>
</div>
<!--<%= javascript_pack_tag 'selectall', 'data-turbolinks-track': 'reload' %>-->