config/routes.rb
Rails.application.routes.draw do
  resources :baanshares,shallow: true do
    member do
      post :pay_all
      post :pay
    end
    resources :wongshares do
      member do
        post :bit
        post :pay
      end
    end
  end
  get 'baanshares/:id', to: 'baanshares#show'
  post '/:id/delete', to: 'baanshares#delete'
  post 'baanshares/new', to: 'baanshares#new'
  get 'summary/', to: "summary#index"
  get 'wongshare/new', to: 'wongshares#new'
  post '/wongshare/new/', to: 'wongshares#new'
  patch 'wongshares/:id/edit', to: 'wongshares#edit'
  devise_for :accounts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "main#index"
  # get '/accounts/sign_in', to: 'sessions#new'
  # post '/accounts/sign_in', to: 'sessions#create'
end

app/views/shared/_card.html.erb
    <% if defined?(baans) && baans.empty? == false%>
    <div class="overflow-x-scroll no-scrollbar">
        <div class="flex justify-start w-full mb-5">
            <% baans.each do |baan|%>
                <% cache baan do%>
                    <%# Card %>
                    <a href=<%= baanshare_path(baan.id)%>>
                    <div class="flex flex-col  md:w-32 h-48 min-w-max mx-3 my-1 text-center rounded-md overflow-hidden shadow-lg border-b-4">
                        <div class=" p-2 w-full h-3/5 bg-gradient-to-b from-gray-50 to-gray-200 text-gray-700">
                            <h1 class="font-bold text-xl tracking-wide"><%=baan.name%></h1>
                            <div class="px-1 my-2 text-left text-xs font-light text-gray-700 text-opacity-90">
                                <p>วงทั้งหมด: <span><%=baan.getWongCount%></span></p>
                                <p>มือเป็น: <span><%=baan.getAvailable%></span></p>
                            </div>
                        </div>
                        <% if baan.getTodayIncome() === '-'%>
                            <div class="flex items-center justify-center w-full h-2/5 
                            bg-gradient-to-b from-gray-400 to-gray-500
                            text-gray-700 text-2xl font-normal ">
                                <h1><span><%=baan.getTodayIncome()%></span></h1>
                            </div>
                        <%elsif baan.getTodayIncome() < 0%>
                            <div class="flex items-center justify-center w-full h-2/5 
                            bg-gradient-to-b from-red-400 to-red-500
                            text-gray-50 text-2xl font-normal ">
                                <h1><span><%=number_to_currency(baan.getTodayIncome(), precision: 0, unit: "", format: "%n %u")%></span></h1>
                            </div>
                        <%else%>
                            <div class="flex items-center justify-center w-full h-2/5 
                            bg-gradient-to-b from-green-400 to-green-500
                            text-gray-50 text-2xl font-normal ">
                                <h1><span><%=number_to_currency(baan.getTodayIncome(), precision: 0, unit: "", format: "%n %u")%></span></h1>
                            </div>
                        <%end%>
                        
                    </div>
                <%end%> 
            <%end%>
        </div>
    </div>
    <%else%>
    <div class="flex justify-center items-center 
        h-48 w-full 
        text-lg text-gray-900 text-center
        my-1  mb-5
        dark:text-gray-50">
        ไม่มีข้อมูล
    </div>

    <%end%>