config/routes.rb
Rails.application.routes.draw do
  resources :baanshares,shallow: true do
    member do
      post :pay_all
      post :pay
    end
    resources :wongshares do
      member do
        post :bit
        post :pay
      end
    end
  end
  get 'baanshares/:id', to: 'baanshares#show'
  post '/:id/delete', to: 'baanshares#delete'
  post 'baanshares/new', to: 'baanshares#new'
  get 'summary/', to: "summary#index"
  get 'wongshare/new', to: 'wongshares#new'
  post '/wongshare/new/', to: 'wongshares#new'
  patch 'wongshares/:id/edit', to: 'wongshares#edit'
  devise_for :accounts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "main#index"
  # get '/accounts/sign_in', to: 'sessions#new'
  # post '/accounts/sign_in', to: 'sessions#create'
end

app/controllers/wongshares_controller.rb
class WongsharesController < ApplicationController
  
  def show
    @wongId = params[:id]
    @baanId = params[:baanId]

    @wong = Wong.find_by_id(@wongId)
    @baanName = Baan.find_by_id(@baanId).name
    @currentCycle = Wong.getCurrentCycleById(@wongId)
    @playDate = Wong.getPlayDateById(@wongId)
    @totalCost = Wong.getTotalCostById(@wongId)
    @alreadyPaid = @wong.paid
    @remaining = @totalCost - @alreadyPaid
    puts "================================"
    puts params[:id]
    puts params[:baanId]
    puts @currentCycle
    puts @playDate
    puts "================================"
  end

  def update
    @wong = Wong.find_by_id(params[:id])
    if @wong.update(params.require(:wong).permit(:income))
      createSummary(@wong)
      flash[:success] = 'อัพเดตดอกเบี้ยที่ได้รับเรียบร้อย!'
      redirect_to wongshare_path(params[:id],:baanId =>params[:baanId])
    elsif @wong.update(params.require(:wong).permit(:name, :wong_type, :deposite, 
      :people, :interest, :fee, :fee_type, :income,
      :start_date, :period, :play_cycle))
      flash[:success] = 'แก้ไขข้อมูลสำเร็จ!!'
      redirect_to wongshare_path(params[:id],:baanId =>params[:baanId])
    else
      flash[:error] = 'แก้ไขไม่ข้อมูลสำเร็จ!!'
      redirect_to edit_wongshare_path(params[:id],:baanId => params[:baanId])
    end
  end

  def new
    @wong = Wong.new()
    @baanId = params[:baanId] if params[:baanId].present?
    Wong.should_validate()
    if params[:wong]
      if @wong.update(params.required(:wong).permit(:name, :wong_type,
                                                  :deposite, :people, :interest,
                                                  :fee, :fee_type, :income, :start_date,
                                                  :period, :play_cycle,:baan_id))
          
        @wong.save! if createSummary(@wong)

        flash[:success] = "สร้างวง #{params[:name]} สำเร็จ !!!"
        redirect_to baanshare_path(@wong.baan_id)
        puts 'nnnnnnnnnnnnnnnnnnnn'
      end
    end
    puts 'nnnnnnnnnnnnnnnnnnnn'
    puts 'nnnnnnnnnnnnnnnnnnnn'
  end

  def edit
    @wong = Wong.find_by_id(params[:id])
    @baanId = params[:baanId]
    puts '99999999999999999'
    puts @wong
    puts params
    puts '99999999999999999'
    if params[:wong]
      if @wong.update(params.require(:wong).permit(:name, :wong_type, :deposite, 
        :people, :interest, :fee, :fee_type, :income,
        :start_date, :period, :play_cycle))
        flash[:success] = 'แก้ไขข้อมูลสำเร็จ!!'
        redirect_to wongshare_path(params[:id],:baanId =>params[:baanId])
      else
        flash[:error] = 'แก้ไขไม่ข้อมูลสำเร็จ!!'
        redirect_to edit_wongshare_path(params[:id],:baanId => params[:baanId])
      end
    end
  end
  
  def pay
    @wong = Wong.find_by_id(params[:id])
    pay = @wong.paid + params[:wong][:cycle].to_i * @wong.interest
    pay += @wong.fee if @wong.fee_type === "จ่ายงวดแรก" && @wong.paid == 0
    if @wong.update(paid: pay)
      @wong.save!
      puts 'ppppppppp'
      puts @wong.paid
      puts params[:wong][:cycle]
      puts 'ppppppppp'
      flash[:success] = 'ชำระเงินสำเร็จ!!!'
    else
      flash[:error] = "มีบางอย่างผิดพลาด กรุณาลองอีกครั้ง."
    end
    redirect_to wongshare_path(@wong.id,:baanId =>params[:baanId])
  end

  def bit
    @wong = Wong.find_by_id(params[:id])
    if @wong.update(params.require(:wong).permit(:bit)) && params[:wong][:bit] != '0'
      @wong.save!
      flash[:success] = "บิทวง#{@wong.name} จำนวน #{@wong.bit} บาทสำเร็จ!!"
      
      if @wong.status == false
        redirect_post pay_baanshare_path(w_id: @wong.id,b_id: params[:baanId]), options: {authenticity_token: :auto}
      else
        redirect_to baanshare_path(params[:baanId])
      end
    else
      flash[:error] = "มีบางอย่างผิดพลาด กรุณาลองอีกครั้ง."
      redirect_to baanshare_path(params[:baanId])
    end
  end

  private
  def isNumeric(str)
    params[:bit] =~ /(0|[1-9][0-9]*)/
  end

  def createSummary(wong)
    today = Date.current.in_time_zone('Asia/Bangkok')
    sum = Summary.where(created: today).first
    if sum.present? == false
      income = wong.getTodayIncome
      outcome = wong.getTodayPaid
      result = wong.getTodayProfit
      Summary.create!(created: today, income: income, outcome: outcome, result: result, account_id: current_account.id)
    else
      income = sum.income + wong.getTodayIncome
      outcome = sum.outcome + wong.getTodayPaid
      result = income - outcome
      sum.update(income: income, outcome: outcome, result: result)
      sum.save!
    end
  end
end

app/helpers/wongshare_helper.rb
module WongshareHelper
end

app/views/wongshares/edit.html.erb
<div class="flex flex-col w-full my-5">
    <div class="flex flex-row justify-between md:justify-center">
        <h1 class="text-center text-2xl">แก้ไขวง</h1>
        <%=link_to 'กลับ', wongshare_path(@wong.id,:baanId =>@baanId), class: '
            md:absolute md:right-5
            min-w-max 
            transition-all duration-200 
            border rounded-sm border-8 border-green-500 
            px-8 mx-1 
            cursor-pointer
            bg-white
            text-md text-gray-900
            shadow-md'%>
    </div>
    <%= form_for @wong, url: edit_wongshare_path(@wong.id, :baanId => @baanId), local: true, class: "h-full" do |f| %>
        <div class="grid grid-cols-2 gap-4 w-full my-5 text-gray-900">
            <div class="flex flex-col w-full">
                <div class="flex flex-col mb-5">
                    <%= f.label 'ชื่อวง:', class: 'font-bold dark:bg-gray-700 dark:text-gray-100 text-lg'%>
                    <%= f.text_field :name, class: 'border-b-2 focus:border-green-500 text-center outline-none bg-white
                                            dark:bg-gray-700 dark:text-gray-100 py' %>
                </div>
                <div class="flex flex-col mb-5">
                    <%= f.label 'ประเภท:', class: 'font-bold dark:bg-gray-700 dark:text-gray-100 text-lg'%>
                    <%= f.select :wong_type,['ขั้นบันได', 'ดอกตาม', 'บิทดอกตาม', 'บิทลดต้น'], {class:''}, class: 'border-b-2 focus:border-green-500 text-center outline-none
                                                                                        dark:bg-gray-700 dark:text-gray-100 py' %>
                </div>
                <div class="flex flex-col mb-5">
                    <%= f.label 'เงินต้น:', class: 'font-bold dark:bg-gray-700 dark:text-gray-100 text-lg'%>
                    <%= f.number_field :deposite, class: 'border-b-2 focus:border-green-500 text-center outline-none bg-white
                                                    dark:bg-gray-700 dark:text-gray-100 py' %>
                </div>
                <div class="flex flex-col mb-5">
                    <%= f.label 'จำนวนมือทั้งหมด:', class: 'font-bold dark:bg-gray-700 dark:text-gray-100 text-lg'%>
                    <%= f.number_field :people, class: 'border-b-2 focus:border-green-500 text-center outline-none bg-white
                                                    dark:bg-gray-700 dark:text-gray-100 py'%>
                </div>
                <div class="flex flex-col mb-5">
                    <%= f.label 'ยอดส่ง:', class: 'font-bold dark:bg-gray-700 dark:text-gray-100 text-lg'%>
                    <%= f.number_field :interest,  class: 'border-b-2 focus:border-green-500 text-center outline-none bg-white
                                                    dark:bg-gray-700 dark:text-gray-100 py'%>
                </div>
                <div class="flex flex-col mb-5">
                    <%= f.label 'ค่าดูแล:', class: 'font-bold dark:bg-gray-700 dark:text-gray-100 text-lg'%>
                    <%= f.number_field :fee,  class: 'border-b-2 focus:border-green-500 text-center outline-none bg-white
                                                    dark:bg-gray-700 dark:text-gray-100 py'%>
                </div>
            </div>
            <div class="flex flex-col w-full">
                <div class="flex flex-col mb-5">
                    <%= f.label 'รูปแบบค่าดูแล:', class: 'font-bold dark:bg-gray-700 dark:text-gray-100 text-lg'%>
                    <%= f.select :fee_type, ["จ่ายงวดแรก", "จ่ายงวดรับเงิน"], {class: 'bg-white py'},  class: 'border-b-2 focus:border-green-500 text-center outline-none bg-white
                                                                        dark:bg-gray-700 dark:text-gray-100 py'%>
                </div>  
                <div class="flex flex-col mb-5">
                    <%= f.label 'ดอกที่ได้รับ:', class: 'font-bold dark:bg-gray-700 dark:text-gray-100 text-lg'%>
                    <%= f.text_field :income, class: 'border-b-2 focus:border-green-500 text-center outline-none bg-white
                                                    dark:bg-gray-700 dark:text-gray-100 py'  %>
                </div>
                <div class="flex flex-col mb-5">
                    <%= f.label 'งวดแรก:', class: 'font-bold dark:bg-gray-700 dark:text-gray-100 text-lg'%>
                    <%= f.date_field :start_date, class: 'border-b-2 focus:border-green-500 text-center outline-none bg-white
                                                         dark:bg-gray-700 dark:text-gray-100 py'  %>
                </div>
                <div class="flex flex-col mb-5">
                    <%= f.label 'ระยะเวลาต่องวด:', class: 'font-bold dark:bg-gray-700 dark:text-gray-100 text-lg'%>
                    <%= f.number_field :period, class: 'border-b-2 focus:border-green-500 text-center outline-none bg-white
                                                        dark:bg-gray-700 dark:text-gray-100 py'  %>
                </div>
                <div class="flex flex-col mb-5">
                    <%= f.label 'งวดที่ได้รับ', class: 'font-bold dark:bg-gray-700 dark:text-gray-100 text-lg'%>
                    <%= f.number_field :play_cycle, class: 'border-b-2 focus:border-green-500 text-center outline-none bg-white 
                                                            dark:bg-gray-700 dark:text-gray-100 py' %>
                </div>
                <%= f.submit 'บันทึก', class: 'min-w-max 
                    transition-all duration-200 
                    border rounded-sm border-8 border-green-500 
                    px-4 py-3
                    cursor-pointer
                    bg-green-500
                    text-lg text-gray-100
                    hover:text-white hover:bg-green-600
                    shadow-md'
                %>
            </div>
        </div>
    <%end%>
</div>

app/views/wongshares/new.html.erb
<div class="flex flex-col w-full my-5">
    <div class="flex flex-row justify-between md:justify-center">
        <h1 class="text-center text-2xl">สร้างวงใหม่</h1>
        <%=link_to 'ยกเลิก', baanshare_path(@baanId), class: '
            md:absolute md:right-5
            min-w-max 
            transition-all duration-200 
            border rounded-sm border-8 border-green-500 
            px-8 mx-1 
            cursor-pointer
            bg-white
            text-md text-gray-900
            shadow-md'%>
    </div>
    <%= form_for @wong, url: wongshare_new_path(), local: true, class: "h-full" do |f| %>
            <%= f.hidden_field :baan_id, value: @baanId%>
            <div class="grid grid-cols-2 gap-4 w-full my-5 text-gray-900 dark:text-white ">
                <div class="flex flex-col w-full">
                    <div class="flex flex-col mb-5">
                        <%= f.label 'ชื่อวง:', class: 'font-bold text-lg'%>
                        <%= f.text_field :name, required: true, placeholder: "กรอกชื่อวง", class: 'border-b-2 focus:border-green-500 text-center outline-none bg-white dark:bg-gray-700 dark:text-gray-100 py' %>
                    </div>
                    <div class="flex flex-col mb-5">
                        <%= f.label 'ประเภท:', class: 'font-bold text-lg'%>
                        <%= f.select :wong_type,['ขั้นบันได', 'ดอกตาม', 'บิทดอกตาม', 'บิทลดต้น'], {required: true, class:'bg-white dark:text-gray-100 '}, class: 'border-b-2 focus:border-green-500 text-center outline-none bg-white dark:bg-gray-700 dark:text-gray-100 dark:bg-gray-700  py' %>
                    </div>
                    <div class="flex flex-col mb-5">
                        <%= f.label 'เงินต้น:', class: 'font-bold text-lg'%>
                        <%= f.number_field :deposite, required: true, placeholder: "ตัวอย่าง: 12345", class: 'border-b-2 focus:border-green-500 text-center outline-none bg-white dark:bg-gray-700 dark:text-gray-100 py' %>
                    </div>
                    <div class="flex flex-col mb-5">
                        <%= f.label 'จำนวนมือทั้งหมด:', class: 'font-bold text-lg'%>
                        <%= f.number_field :people, required: true, placeholder: "ตัวอย่าง: 50", class: 'border-b-2 focus:border-green-500 text-center outline-none bg-white dark:bg-gray-700 dark:text-gray-100 py'%>
                    </div>
                    <div class="flex flex-col mb-5">
                        <%= f.label 'ยอดส่ง:', class: 'font-bold text-lg'%>
                        <%= f.number_field :interest, required: true, placeholder: "ตัวอย่าง: 1000", class: 'border-b-2 focus:border-green-500 text-center outline-none bg-white dark:bg-gray-700 dark:text-gray-100 py'%>
                    </div>
                    <div class="flex flex-col mb-5">
                        <%= f.label 'ค่าดูแล:', class: 'font-bold text-lg'%>
                        <%= f.number_field :fee, required: true, placeholder: "ตัวอย่าง: 1000", class: 'border-b-2 focus:border-green-500 text-center outline-none bg-white dark:bg-gray-700 dark:text-gray-100 py'%>
                    </div>
                </div>
                <div class="flex flex-col w-full">
                    <div class="flex flex-col mb-5">
                        <%= f.label 'รูปแบบค่าดูแล:', class: 'font-bold text-lg'%>
                        <%= f.select :fee_type, ["จ่ายงวดแรก", "จ่ายงวดรับเงิน"], {required: true, class: 'bg-white dark:text-gray-100 py'},  class: 'border-b-2 focus:border-green-500 text-center outline-none bg-white dark:bg-gray-700 py'%>
                    </div>  
                    <div class="flex flex-col mb-5">
                        <%= f.label 'ดอกที่ได้รับ:', class: 'font-bold text-lg'%>
                        <%= f.number_field :income,min: 0,required: true, class: 'border-b-2 focus:border-green-500 text-center outline-none bg-white dark:bg-gray-700 dark:text-gray-100 py'  %>
                    </div>
                    <div class="flex flex-col mb-5">
                        <%= f.label 'งวดแรก:', class: 'font-bold text-lg'%>
                        <%= f.date_field :start_date, required: true, class: 'border-b-2 focus:border-green-500 text-center outline-none bg-white dark:bg-gray-700 dark:text-gray-100 py'  %>
                    </div>
                    <div class="flex flex-col mb-5">
                        <%= f.label 'ระยะเวลาต่องวด:', class: 'font-bold text-lg'%>
                        <%= f.number_field :period, required: true, placeholder: "หน่วยวัน, ตัวอย่าง: 2 ", class: 'border-b-2 focus:border-green-500 text-center outline-none bg-white dark:bg-gray-700 dark:text-gray-100 py'  %>
                    </div>
                    <div class="flex flex-col mb-5">
                        <%= f.label 'งวดที่ได้รับ', class: 'font-bold text-lg'%>
                        <%= f.number_field :play_cycle, class: 'border-b-2 focus:border-green-500 text-center outline-none bg-white dark:bg-gray-700 dark:text-gray-100 py' %>
                    </div>
                    <%= f.submit 'สร้างวง', class: 'min-w-max 
                        transition-all duration-200 
                        border rounded-sm border-8 border-green-500 
                        px-4 py-3
                        cursor-pointer
                        bg-green-500
                        text-lg text-gray-100
                        hover:text-white hover:bg-green-600
                        shadow-md'
                    %>
                </div>
            </div>
        <%end%>
    </div>

app/views/wongshares/show.html.erb
<div class="flex flex-col w-full my-5 text-black dark:text-gray-50">
    <div class="flex flex-row flex-wrap justify-between content-center">
        <div class="flex flex-row">
            <h1 class="text-xl min-w-max">รายละเอียดวงแชร์: <span class="tracking-wider font-bold dark:text-gray-50 text-gray-800"><%= @wong.name%></span></h1>  
            <%if @wong.unpayCycle() != 0%>
                <h1 class="min-w-max mx-5 flex flex-row ">คุณมียอดค้างชำระ (<%= @wong.unpayCycle()%> งวด):  
                    <span class="tracking-wide text-gray-900 font-semibold">
                        <%= form_with model: @wong, url: pay_wongshare_path(@wong.id,:baanId => @baanId), method: :post, local: true, 
                        class: "flex flex-row min-w-max ml-2" do |f| %>
                                <%=f.number_field :cycle, max: @wong.unpayCycle(), value: @wong.unpayCycle(), class: 'border-b-2 focus:border-green-500 text-center outline-none w-20'%>
                                <%=f.submit 'ชำระ', class: '
                                transition-all duration-200 
                                border border-green-500 rounded-sm
                                mx-2 px-4 cursor-pointer 
                                text-md text-gray-100 
                                bg-green-500
                                hover:text-white hover:bg-green-600 hover:border-green-600
                                shadow-md'%>
                            <% end %>
                    </span>
                </h1>
            <%end%>
        </div>
        <div class="flex items-center">
            <%= link_to 'กลับ', baanshare_path(@baanId),class: '
            min-w-max
            max-h-full 
            transition-all duration-200 
            border rounded-sm border-8 border-green-500 
            px-8 mx-1 
            cursor-pointer
            bg-white
            text-md text-gray-900
            shadow-md'%>
            <%= link_to 'แก้ไข', edit_wongshare_path(@wong.id,:baanId => @baanId), class: ' 
            transition-all duration-200 
            border rounded-sm border-8 border-green-500 
            px-8 mx-1 
            cursor-pointer
            bg-green-500
            text-md text-gray-100
            hover:text-white hover:bg-green-600 hover:border-green-600
            shadow-md'%>
        </div>
    </div>
    <div class="grid grid-cols-2 mt-5 h-4/5 text-lg ">
        <div class="flex flex-col justify-around">
            <div><h1>บ้าน:  <span class="tracking-wide dark:text-gray-50 text-gray-900 font-semibold"><%= @baanName%></span></h1></div>
            <div><h1>ประเภท:  <span class="tracking-wide dark:text-gray-50 text-gray-900 font-semibold"><%= @wong.wong_type%></span></h1></div>
            <div><h1>เงินต้น:  <span class="tracking-wide dark:text-gray-50 text-gray-900 font-semibold"><%= @wong.deposite%></span> บาท</h1></div>
            <div><h1>จำนวนมือทั้งหมด:  <span class="tracking-wide dark:text-gray-50 text-gray-900 font-semibold"><%= @wong.people%></span> คน</h1></div>
            <div><h1>ยอดส่ง:  <span class="tracking-wide dark:text-gray-50 text-gray-900 font-semibold"><%= @wong.interest%></span> บาท</h1></div>
            <div><h1>ค่าดูแล:  <span class="tracking-wide dark:text-gray-50 text-gray-900 font-semibold"><%= @wong.fee%></span> บาท</h1></div>
            <div><h1>รูปแบบค่าดูแล:  <span class="tracking-wide dark:text-gray-50 text-gray-900 font-semibold"><%= @wong.fee_type%></span></h1></div>
        </div>
        <div class="flex flex-col justify-around">
            <div>
                <% if @wong.wong_type === "ขั้นบันได" || @wong.wong_type === "ดอกตาม"%>
                    <h1 class="opacity-50">ดอกที่ได้รับ:  <span class="pointer-events-none tracking-wide text-gray-900 font-semibold"><%= form_with model: @wong, url: wongshare_path(@wong.id,:baanId =>@baanId), method: :patch, local: true, class: "inline" do |f| %>
                    <%=f.text_field :income, class: 'border w-20 text-center outline-none '%>
                    <%=f.submit 'ยืนยัน', class: '
                    transition-all duration-200 
                    border border-green-500 rounded-sm
                    mx-1 px-4 cursor-pointer 
                    text-md text-gray-100 
                    bg-green-500
                    hover:text-white hover:bg-green-600 hover:border-green-600
                    shadow-md'%>
                    <% end %>
                    </span></h1>
                <%else%>
                    <h1>ดอกที่ได้รับ:  <span class="tracking-wide text-gray-900 font-semibold"><%= form_with model: @wong, url: wongshare_path(@wong.id,:baanId =>@baanId), method: :patch, local: true, class: "inline" do |f| %>
                        <%=f.text_field :income, class: 'border-b-2 w-20 focus:border-green-500 text-center outline-none'%>
                        <%=f.submit 'ยืนยัน', class: '
                        transition-all duration-200 
                        border border-green-500 rounded-sm
                        mx-1 px-4 cursor-pointer
                        text-md text-gray-100 
                        bg-green-500
                        hover:text-white hover:bg-green-600 hover:border-green-600
                        shadow-md'%>
                    <% end %>
                    </span></h1>
                <%end%>
            </div>
            <div><h1>งวดแรก:  <span class="tracking-wide dark:text-gray-50 text-gray-900 font-semibold"><%= @wong.start_date%></span></h1></div>
            <div><h1>ระยะเวลาต่องวด:  <span class="tracking-wide dark:text-gray-50 text-gray-900 font-semibold"><%= @wong.period%></span> วัน</h1></div>
            <div><h1>งวดปัจจุบัน:  <span class="tracking-wide dark:text-gray-50 text-gray-900 font-semibold"><%= @wong.getCurrentCycle()%></span></h1></div>
            <div><h1>งวดคงเหลือ:  <span class="tracking-wide dark:text-gray-50 text-gray-900 font-semibold"><%= @wong.people - @wong.getCurrentCycle()%></span> งวด</h1></div>
            <div><h1>งวดได้รับ:  <span class="tracking-wide dark:text-gray-50 text-gray-900 font-semibold"><%= @wong.play_cycle%></span></h1></div>
            <div><h1>วันที่เปียร์:  <span class="tracking-wide dark:text-gray-50 text-gray-900 font-semibold"><%= @wong.getPlayDate()%></span></h1></div>
        </div>
    </div>
    <div class="flex flex-row flex-warp items-end justify-evenly h-1/4 text-lg">
        <div class="shadow-md rounded py-4 px-5 bg-gradient-to-b from-red-400 to-red-500"><h1 class="text-gray-900">ยอดชำระทั้งหมด:  <span class="tracking-wide text-gray-900 font-semibold"><%= number_to_currency(@wong.getTotalCost(), precision: 0, format: "%n")%></span></h1></div>
        <div class="shadow-md rounded py-4 px-5 bg-gradient-to-b from-yellow-400 to-yellow-500"><h1 class="text-gray-900">ยอดชำระแล้ว:  <span class="tracking-wide text-gray-900 font-semibold"><%= number_to_currency(@wong.paid, precision: 0, unit: "", format: "%n")%></span></h1></div>
        <div class="shadow-md rounded py-4 px-5 bg-gradient-to-b from-gray-400 to-gray-500"><h1 class="text-gray-900">ยอดชำระคงเหลือ:  <span class="tracking-wide text-gray-900 font-semibold"><%= number_to_currency(@wong.getTotalCost() - @wong.paid, precision: 0, format: "%n")%></span></h1></div>
        
        <% if (@wong.deposite + @wong.income) - @wong.getTotalCost() > 0%>
            <div class="shadow-md rounded py-4 px-5 bg-green-400"><h1 class="text-gray-900">กำไรหลังจบวง:  <span class="tracking-wide text-gray-900 font-bold">
            +<%=(@wong.deposite + @wong.income) - @wong.getTotalCost()%>
            </span></h1>
            </div>
        <%else%>
            <div class="shadow-md rounded py-4 px-5 bg-gradient-to-b from-red-400 to-red-500"><h1 class="text-gray-900">กำไรหลังจบวง:  <span class="tracking-wide text-gray-900 font-bold">
                <%=(@wong.deposite + @wong.income) - @wong.getTotalCost()%>
                </span></h1>
            </div>
        <%end%>
    </div>
</div>